export const PAGINATED_INVOICE_EXAMPLE = {
  data: [
    {
      invoiceId: 100,
      code: '00012',
      observations: 'Esta factura corresponde a la venta de miguel gonzalez',
      invoiceElectronic: true,
      subtotalWithoutTax: '10000',
      subtotalWithTax: '100000',
      total: '110000',
      totalTaxes: 10000,
      transfer: 10000,
      cash: 100000,
      invoiceType: {
        invoiceTypeId: 2,
        code: 'FV',
        name: 'FACTURA DE VENTA',
      },
      payType: {
        payTypeId: 2,
        code: 'PAG',
        name: 'PAGADO',
      },
      paidType: {
        paidTypeId: 2,
        code: 'EFE',
        name: 'EFECTIVO',
      },
      employee: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
      },
      user: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
        identificationType: {
          identificationTypeId: 2,
          code: 'CC',
          name: 'CEDULA DE CIUDADANIA',
        },
      },
      invoiceDetails: [
        {
          invoiceDetailId: 2,
          amount: 5,
          priceWithoutTax: '1000',
          priceWithTax: '1100',
          subtotal: '5500',
          taxe: 'IVA 10%',
          startDate: '2024-06-01',
          endDate: '2024-06-01',
          product: {
            productId: 2,
            code: 'COC',
            name: 'Coca Cola 500ml',
          },
          accommodation: {
            accommodationId: 2,
            code: 'CAB1',
            name: 'Cabaña 1',
          },
          excursion: {
            excursionId: 2,
            code: 'PAS',
            name: 'Pasadía niños',
          },
        },
      ],
    },
    {
      invoiceId: 100,
      code: '00012',
      observations: 'Esta factura corresponde a la venta de miguel gonzalez',
      invoiceElectronic: true,
      subtotalWithoutTax: '10000',
      subtotalWithTax: '100000',
      total: '110000',
      totalTaxes: 10000,
      transfer: 10000,
      cash: 100000,
      invoiceType: {
        invoiceTypeId: 2,
        code: 'FV',
        name: 'FACTURA DE VENTA',
      },
      payType: {
        payTypeId: 2,
        code: 'PAG',
        name: 'PAGADO',
      },
      paidType: {
        paidTypeId: 2,
        code: 'EFE',
        name: 'EFECTIVO',
      },
      employee: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
      },
      user: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
        identificationType: {
          identificationTypeId: 2,
          code: 'CC',
          name: 'CEDULA DE CIUDADANIA',
        },
      },
      invoiceDetails: [
        {
          invoiceDetailId: 2,
          amount: 5,
          priceWithoutTax: '1000',
          priceWithTax: '1100',
          subtotal: '5500',
          taxe: 'IVA 10%',
          startDate: '2024-06-01',
          endDate: '2024-06-01',
          product: {
            productId: 2,
            code: 'COC',
            name: 'Coca Cola 500ml',
          },
          accommodation: {
            accommodationId: 2,
            code: 'CAB1',
            name: 'Cabaña 1',
          },
          excursion: {
            excursionId: 2,
            code: 'PAS',
            name: 'Pasadía niños',
          },
        },
      ],
    },
    {
      invoiceId: 100,
      code: '00012',
      observations: 'Esta factura corresponde a la venta de miguel gonzalez',
      invoiceElectronic: true,
      subtotalWithoutTax: '10000',
      subtotalWithTax: '100000',
      total: '110000',
      totalTaxes: 10000,
      transfer: 10000,
      cash: 100000,
      invoiceType: {
        invoiceTypeId: 2,
        code: 'FV',
        name: 'FACTURA DE VENTA',
      },
      payType: {
        payTypeId: 2,
        code: 'PAG',
        name: 'PAGADO',
      },
      paidType: {
        paidTypeId: 2,
        code: 'EFE',
        name: 'EFECTIVO',
      },
      employee: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
      },
      user: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
        identificationType: {
          identificationTypeId: 2,
          code: 'CC',
          name: 'CEDULA DE CIUDADANIA',
        },
      },
      invoiceDetails: [
        {
          invoiceDetailId: 2,
          amount: 5,
          priceWithoutTax: '1000',
          priceWithTax: '1100',
          subtotal: '5500',
          taxe: 'IVA 10%',
          startDate: '2024-06-01',
          endDate: '2024-06-01',
          product: {
            productId: 2,
            code: 'COC',
            name: 'Coca Cola 500ml',
          },
          accommodation: {
            accommodationId: 2,
            code: 'CAB1',
            name: 'Cabaña 1',
          },
          excursion: {
            excursionId: 2,
            code: 'PAS',
            name: 'Pasadía niños',
          },
        },
      ],
    },
    {
      invoiceId: 100,
      code: '00012',
      observations: 'Esta factura corresponde a la venta de miguel gonzalez',
      invoiceElectronic: true,
      subtotalWithoutTax: '10000',
      subtotalWithTax: '100000',
      total: '110000',
      totalTaxes: 10000,
      transfer: 10000,
      cash: 100000,
      invoiceType: {
        invoiceTypeId: 2,
        code: 'FV',
        name: 'FACTURA DE VENTA',
      },
      payType: {
        payTypeId: 2,
        code: 'PAG',
        name: 'PAGADO',
      },
      paidType: {
        paidTypeId: 2,
        code: 'EFE',
        name: 'EFECTIVO',
      },
      employee: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
      },
      user: {
        userId: 'eae05031-a181-4175-b09c-90177ef87f9b',
        firstName: 'MIGUEL CAMILO',
        lastName: 'GONZALEZ RAMIREZ',
        identificationNumber: '1120055420',
        identificationType: {
          identificationTypeId: 2,
          code: 'CC',
          name: 'CEDULA DE CIUDADANIA',
        },
      },
      invoiceDetails: [
        {
          invoiceDetailId: 2,
          amount: 5,
          priceWithoutTax: '1000',
          priceWithTax: '1100',
          subtotal: '5500',
          taxe: 'IVA 10%',
          startDate: '2024-06-01',
          endDate: '2024-06-01',
          product: {
            productId: 2,
            code: 'COC',
            name: 'Coca Cola 500ml',
          },
          accommodation: {
            accommodationId: 2,
            code: 'CAB1',
            name: 'Cabaña 1',
          },
          excursion: {
            excursionId: 2,
            code: 'PAS',
            name: 'Pasadía niños',
          },
        },
      ],
    },
  ],
};

export const GET_INVOICE_EXAMPLE = {
  invoiceId: 2,
  code: '0023',
  subtotalWithTax: '0.00',
  total: '0.00',
  startDate: '2025-05-27',
  endDate: '2025-05-30',
  createdAt: '2025-05-28T03:30:48.678Z',
  updatedAt: '2025-05-28T03:30:48.678Z',
  deletedAt: null,
  invoiceType: {
    invoiceTypeId: 1,
    code: 'FV',
    name: 'Factura de Venta',
    createdAt: '2025-05-28T03:21:13.334Z',
    updatedAt: '2025-05-28T03:21:13.334Z',
    deletedAt: null,
  },
  invoiceDetails: [],
};

export const CREATE_RELATED_DATA_INVOICE_EXAMPLE = {
  categoryType: [
    { categoryTypeId: '1', code: 'MEC', name: 'MECATO' },
    { categoryTypeId: '2', code: 'BAR', name: 'BAR' },
  ],
  invoiceType: [
    { invoiceTypeId: '1', code: 'FV', name: 'FACTURA DE VENTA' },
    { invoiceTypeId: '2', code: 'FC', name: 'FACTURA DE COMPRA' },
  ],
  taxeType: [
    { taxeTypeId: '1', name: 'IVA 19%', percentage: 19 },
    { taxeTypeId: '2', name: 'IVA 0%', percentage: 0 },
  ],
  payType: [
    { payTypeId: '1', code: 'EF', name: 'EFECTIVO' },
    { payTypeId: '2', code: 'TC', name: 'TARJETA DE CRÉDITO' },
  ],
  paidType: [
    { paidTypeId: '1', code: 'PA', name: 'PAGADO' },
    { paidTypeId: '2', code: 'PP', name: 'POR PAGAR' },
  ],
  identificationType: [
    { identificationTypeId: '1', code: 'CC', name: 'CEDULA DE CIUDADANIA' },
    { identificationTypeId: '2', code: 'NIT', name: 'NIT' },
  ],
  additionalType: [
    { additionalTypeId: '1', code: '1 PERSONA', value: 100000 },
    { additionalTypeId: '2', code: '2 PERSONAS', value: 200000 },
  ],
  discountType: [
    {
      discountTypeId: '1',
      code: 5000,
      name: 5000,
      percent: 0,
    },
    { discountTypeId: '2', code: 10000, name: 10000, percent: 0 },
  ],
};
